# Configuration documentation:
#   https://embarkstudios.github.io/cargo-deny/index.html
[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "MIT",
    "Unicode-3.0",
    "Zlib",
]
